/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BanSach.ui;

import BanSach.util.XAuth;
import java.awt.CardLayout;

/**
 *
 * @author ADMIN
 */
public class BanSach extends javax.swing.JFrame {

    private CardLayout cardLayout = new CardLayout();

    /**
     * Creates new form BanSach
     */
    public BanSach() {
        initComponents();
        this.initPanel();
        initRole(); // Phân quyền cho nút
    }

    public void showChangePasswordJDialog(java.awt.Frame parent) {
        ChangePasswordJDialog dialog = new ChangePasswordJDialog(parent, true);
        dialog.open(); // mở chính giữa màn hình
        dialog.setVisible(true); // hiển thị form
    }

    private void initPanel() {

        this.mainPanel.setLayout(cardLayout);

        // Thêm panel trống mặc định
        RongJPanel rongJPanel = new RongJPanel();
        mainPanel.add("RONG", rongJPanel);
        // Thêm panel quản lý thể loại
        CategoryManagerJPanel categoryManagerJPanel = new CategoryManagerJPanel();
        mainPanel.add("CATEGORY_MANAGER", categoryManagerJPanel);

        CardManagerJPanel cardManagerJPanel = new CardManagerJPanel();
        mainPanel.add("CARD_MANAGER", cardManagerJPanel); // dùng key khác

        BookManagerJPanel drinkManagerJPanel = new BookManagerJPanel();
        mainPanel.add("DRINK_MANAGER", drinkManagerJPanel); // dùng key khác

        BillManagerJPanel billManagerJPanel = new BillManagerJPanel();
        mainPanel.add("BILL_MANAGER", billManagerJPanel); // dùng key khác

        EmployeeManagerJDialogJPanel userManagerJDialogJPanel = new EmployeeManagerJDialogJPanel();
        mainPanel.add("USER_MANAGER", userManagerJDialogJPanel); // dùng key khác

        RevenueManagerJPanel revenueManagerJPanel = new RevenueManagerJPanel();
        mainPanel.add("REVENUE_MANAGER", revenueManagerJPanel); // dùng key khác

         PromotionJPanel promotionJPanel  = new PromotionJPanel ();
       mainPanel.add("PROMOTION", promotionJPanel ); // dùng key khác
        
    }

    private void initRole() {
        if (!XAuth.user.isRole()) { // nếu không phải admin
            btnqlnhanvien.setVisible(false);  // Ẩn nút Quản lý nhân viên
            btnqlkm.setVisible(false);         // Ẩn nút Quản lý khuyến mãi
            btndanhthu.setVisible(false);      // Ẩn nút Thống kê doanh thu
            btnloaisach.setVisible(false);
            btnsach.setVisible(false);
            btncard.setVisible(false);
            btndonhang.setVisible(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        m = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnsach = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnloaisach = new javax.swing.JButton();
        btndonhang = new javax.swing.JButton();
        btncard = new javax.swing.JButton();
        btnqlnhanvien = new javax.swing.JButton();
        btnqlkm = new javax.swing.JButton();
        btndanhthu = new javax.swing.JButton();
        btntrangchu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setText("BÁN HÀNG ");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAccount.setText("Xem lịch sử");
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        btnProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProduct.setText("Đổi mật khẩu");
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });

        btnsach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsach.setText("Quản lý sách");
        btnsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsachActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bansach/icon/hinh2.png"))); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Quản lý");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nhân Viên");

        btnloaisach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnloaisach.setText("Quản lý thể loại sách");
        btnloaisach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloaisachActionPerformed(evt);
            }
        });

        btndonhang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndonhang.setText("Quản lý đơn hàng");
        btndonhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonhangActionPerformed(evt);
            }
        });

        btncard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncard.setText("Quản lý thẻ thành viên ");
        btncard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncardActionPerformed(evt);
            }
        });

        btnqlnhanvien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnqlnhanvien.setText("Quản lý nhân viên");
        btnqlnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlnhanvienActionPerformed(evt);
            }
        });

        btnqlkm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnqlkm.setText("Quản lý khuyến mãi");
        btnqlkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlkmActionPerformed(evt);
            }
        });

        btndanhthu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndanhthu.setText("Thống kê doanh thu");
        btndanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndanhthuActionPerformed(evt);
            }
        });

        btntrangchu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btntrangchu.setText("TRANG CHỦ ");
        btntrangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrangchuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mLayout = new javax.swing.GroupLayout(m);
        m.setLayout(mLayout);
        mLayout.setHorizontalGroup(
            mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(btnsach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnloaisach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndonhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncard, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(btnqlnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnqlkm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btndanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jSeparator1))
                    .addGroup(mLayout.createSequentialGroup()
                        .addGroup(mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(btntrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mLayout.setVerticalGroup(
            mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntrangchu)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProduct)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnloaisach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndonhang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqlnhanvien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqlkm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndanhthu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(m, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btndanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndanhthuActionPerformed
        // TODO add your handling code here:
        cardLayout.show(mainPanel, "REVENUE_MANAGER");
    }//GEN-LAST:event_btndanhthuActionPerformed

    private void btnsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsachActionPerformed
        // TODO add your handling code here:       
        cardLayout.show(mainPanel, "DRINK_MANAGER");
    }//GEN-LAST:event_btnsachActionPerformed

    private void btnloaisachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloaisachActionPerformed
        // TODO add your handling code here:
        cardLayout.show(mainPanel, "CATEGORY_MANAGER");
    }//GEN-LAST:event_btnloaisachActionPerformed

    private void btncardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(mainPanel, "CARD_MANAGER");
    }//GEN-LAST:event_btncardActionPerformed

    private void btndonhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonhangActionPerformed
        // TODO add your handling code here:
        cardLayout.show(mainPanel, "BILL_MANAGER");
    }//GEN-LAST:event_btndonhangActionPerformed

    private void btnqlnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlnhanvienActionPerformed
        // TODO add your handling code here:
        cardLayout.show(mainPanel, "USER_MANAGER");
    }//GEN-LAST:event_btnqlnhanvienActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        // TODO add your handling code here:
        this.showChangePasswordJDialog(this);
    }//GEN-LAST:event_btnProductActionPerformed

    private void btntrangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrangchuActionPerformed
        // TODO add your handling code here:
         cardLayout.show(mainPanel, "RONG"); 
    }//GEN-LAST:event_btntrangchuActionPerformed

    private void btnqlkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlkmActionPerformed
        // TODO add your handling code here:
         cardLayout.show(mainPanel, "PROMOTION"); 
    }//GEN-LAST:event_btnqlkmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                loginJDialog login = new loginJDialog(null, true);
                login.setVisible(true);

                // Khi form login đóng thì kiểm tra xem user đã đăng nhập chưa
                if (XAuth.user != null) {
                    new BanSach().setVisible(true);  // mở form chính
                } else {
                    System.exit(0);  // thoát nếu không đăng nhập
                }
            }
            // viết thêm một hàm kiểm tra tài khoảng 
            //với quyền admin cao nhất trong db chưa 
            // nếu chưa thì tạo cho hệ thống 1 tài khoảng 
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btncard;
    private javax.swing.JButton btndanhthu;
    private javax.swing.JButton btndonhang;
    private javax.swing.JButton btnloaisach;
    private javax.swing.JButton btnqlkm;
    private javax.swing.JButton btnqlnhanvien;
    private javax.swing.JButton btnsach;
    private javax.swing.JButton btntrangchu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel m;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
