/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package BanSach.ui;

import BanSach.Dao.impl.EmployeeDAOImpl;
import BanSach.entity.Employee;
import BanSach.util.XAuth;
import javax.swing.JOptionPane;
import BanSach.Dao.EmployeeDAO;
import BanSach.util.EmailUtil;
import java.io.IOException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;

/**
 *
 * @author ADMIN
 */

public class GetFamiliarJDialog extends javax.swing.JDialog {
  private boolean isFirstConfirmation = true; // Theo dõi trạng thái xác nhận
    /**
     * Creates new form GetFamiliarJDialog
     */
    public GetFamiliarJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        txtSecurityAnswer.setEnabled(false);
        txtNewPassword.setEnabled(false);
        btnDoiMatKhau.setEnabled(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtSecurityAnswer = new javax.swing.JTextField();
        txtNewPassword = new javax.swing.JPasswordField();
        btnxacnhan = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblSecurityQuestion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quên mật khẩu ");

        jLabel1.setText("Tên đăng nhập");

        jLabel2.setText("câu hỏi bảo mật");

        jLabel3.setText("Mật khẩu mới ");

        btnxacnhan.setText("Xác nhận");
        btnxacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxacnhanActionPerformed(evt);
            }
        });

        btnDoiMatKhau.setText("Đổi mật khẩu ");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("QUÊN MẬT KHẨU ");

        lblSecurityQuestion.setBackground(new java.awt.Color(51, 51, 51));
        lblSecurityQuestion.setForeground(new java.awt.Color(255, 0, 153));
        lblSecurityQuestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(btnxacnhan)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(btnDoiMatKhau))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblSecurityQuestion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSecurityQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxacnhan)
                    .addComponent(btnDoiMatKhau))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnxacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxacnhanActionPerformed
        String username = txtUsername.getText().trim();

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên đăng nhập.");
            return;
        }

        if (isFirstConfirmation) {
            // Xác nhận lần đầu: Kiểm tra username và hiển thị câu hỏi bảo mật
            XAuth.user = dao.findByUsername(username);

            if (XAuth.user != null) {
                String question = XAuth.user.getSecurityQuestion();
                if (question == null || question.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Tài khoản này chưa thiết lập câu hỏi bảo mật.");
                    return;
                }
                lblSecurityQuestion.setText(question);
                txtSecurityAnswer.setEnabled(true);
                isFirstConfirmation = false; // Chuyển sang trạng thái xác nhận lần hai
            } else {
                JOptionPane.showMessageDialog(this, "Tên đăng nhập không tồn tại.");
            }
        } else {
            // Xác nhận lần hai: Kiểm tra câu trả lời bảo mật
            String enteredAnswer = txtSecurityAnswer.getText().trim();

            if (enteredAnswer.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập câu trả lời bảo mật.");
                return;
            }

            XAuth.user = dao.findByUsername(XAuth.user.getUsername());
            String storedAnswer = XAuth.user.getSecurityAnswer();

            if (!enteredAnswer.equalsIgnoreCase(storedAnswer)) {
                JOptionPane.showMessageDialog(this, "Câu trả lời bảo mật không đúng.");
                return;
            }

            txtNewPassword.setEnabled(true);
            btnDoiMatKhau.setEnabled(true);
            txtSecurityAnswer.setEnabled(false); // Vô hiệu hóa ô trả lời để tránh chỉnh sửa
            btnxacnhan.setEnabled(false); // Vô hiệu hóa nút Xác nhận để tránh nhấn lại
        }
    }//GEN-LAST:event_btnxacnhanActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        if (XAuth.user == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng xác minh trước.");
            return;
        }

        String enteredAnswer = txtSecurityAnswer.getText().trim();
        String newPassword = new String(txtNewPassword.getPassword()).trim();

        if (enteredAnswer.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập câu trả lời bảo mật.");
            return;
        }

        XAuth.user = dao.findByUsername(XAuth.user.getUsername());
        String storedAnswer = XAuth.user.getSecurityAnswer();

        if (!enteredAnswer.equalsIgnoreCase(storedAnswer)) {
            JOptionPane.showMessageDialog(this, "Câu trả lời bảo mật không đúng.");
            return;
        }

        if (newPassword.length() < 4) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải có ít nhất 4 ký tự.");
            return;
        }

        boolean result = dao.updatePassword(XAuth.user.getUsername(), newPassword);
        if (result) {
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công.");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thất bại.");
        }

    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(GetFamiliarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
        GetFamiliarJDialog dialog = new GetFamiliarJDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnxacnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblSecurityQuestion;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtSecurityAnswer;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
EmployeeDAO dao = new EmployeeDAOImpl();
}
