/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BanSach.ui;

import BanSach.Dao.PromotionDAO;
import BanSach.Dao.impl.BookDAOImpl;
import BanSach.entity.Promotion;
import javax.swing.table.DefaultTableModel;
import BanSach.entity.Promotion;
import BanSach.Dao.impl.PromotionDAOImpl;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class PromotionJPanel extends javax.swing.JPanel implements PromotionControlle {

    private CardLayout cardLayout = new CardLayout();

    /**
     * Creates new form PromotionJPanel
     */
    public PromotionJPanel() {
        initComponents();
        init();
        loadBookIDs();

    }

    private void init() {
        this.panel.setLayout(cardLayout);
       PromotionBookJPanel  promotionBookJPanel  = new PromotionBookJPanel ();
        panel.add("PROMOTION", promotionBookJPanel );
        
        
        
        
        tableModel.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Khuyến Mãi", "Tên chương trình", "ngày bắt đầu ", "Ngày kết thúc", "giảm giá ", "trạng thái "
                }
        ));
        phamtram.setMinimum(0);
        phamtram.setMaximum(100);
        phamtram.setMajorTickSpacing(10);
        phamtram.setPaintTicks(true);
        phamtram.setPaintLabels(true);

        fillToTable();
    }

    private void loadBookIDs() {
        try {
            List<String> bookIDs = new BookDAOImpl().findAllBookIDs(); // Giả sử bạn có DAO như vậy
            cbopromotion.removeAllItems();
            for (String id : bookIDs) {
                cbopromotion.addItem(id);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi load danh sách mã sách: " + e.getMessage());
        }
    }

    PromotionDAO dao = new PromotionDAOImpl();
    List<Promotion> items = List.of();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbopromotion = new javax.swing.JComboBox<>();
        txtpromotionName = new javax.swing.JTextField();
        startDate = new javax.swing.JTextField();
        txtpromotionID = new javax.swing.JTextField();
        endDate = new javax.swing.JTextField();
        phamtram = new javax.swing.JSlider();
        panel = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnmasach = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModel = new javax.swing.JTable();
        btnnhunghoatdong = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ KHUYẾN MÃI");

        jLabel2.setText("Tên chương trình ");

        jLabel3.setText("Ngày bắt đầu ");

        jLabel4.setText("Mã sách áp dụng ");

        jLabel5.setText("Ngày kết thúc");

        jLabel6.setText("Giảm giá ");

        jLabel7.setText("Chương trình sắp diễn ra ");

        cbopromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbopromotionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        btnCreate.setText("Thêm ");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sửa ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Nhập mới ");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel8.setText("Mã khuyến mãi");

        tableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi ", "Tên chương trình  ", "Ngày Bắt đầu ", "Ngày kết thúc", "Giảm giá ", "Trạng thái "
            }
        ));
        tableModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableModelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableModel);

        btnnhunghoatdong.setText("Ngừng hoạt động");
        btnnhunghoatdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhunghoatdongActionPerformed(evt);
            }
        });

        jButton1.setText("Hiển thị danh sách ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(211, 211, 211))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel4)
                                        .addGap(19, 19, 19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpromotionName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnmasach, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpromotionID, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreate)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(143, 143, 143)
                                .addComponent(btnnhunghoatdong))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addComponent(cbopromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(phamtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbopromotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtpromotionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpromotionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnmasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(phamtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreate)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnClear)
                            .addComponent(btnnhunghoatdong)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableModelMouseClicked
        // TODO add your handling code here:
        int row = tableModel.getSelectedRow();
        if (row >= 0) {
            PromotionDAOImpl dao = new PromotionDAOImpl();
            String id = (String) tableModel.getValueAt(row, 0); // Giả sử cột đầu là ID
            Promotion p = dao.findById(id);
            setForm(p);
        }
    }//GEN-LAST:event_tableModelMouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        this.create();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnnhunghoatdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhunghoatdongActionPerformed
        // TODO add your handling code here:
        int row = tableModel.getSelectedRow();
        if (row >= 0) {
            String id = (String) tableModel.getValueAt(row, 0);
            PromotionDAOImpl dao = new PromotionDAOImpl();
            Promotion p = dao.findById(id);
            if (p != null) {
                p.setStatus(false); // Đặt trạng thái thành "Ngừng hoạt động"
                dao.update(p);
                fillToTable();
                JOptionPane.showMessageDialog(this, "Đã ngừng hoạt động khuyến mãi!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khuyến mãi để ngừng hoạt động!");
        }
    }//GEN-LAST:event_btnnhunghoatdongActionPerformed

    private void cbopromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbopromotionActionPerformed
        // TODO add your handling code here:
        String selectedCategory = (String) cbopromotion.getSelectedItem();
        if (selectedCategory != null) {
            btnmasach.setText(selectedCategory); // Cập nhật jTextField5
        }
    }//GEN-LAST:event_cbopromotionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         cardLayout.show(panel, "PROMOTION");
    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public void open() {
        this.fillToTable();
        this.clear();
    }

    @Override
    public void setForm(Promotion entity) {
        txtpromotionID.setText(entity.getPromotionID() != null ? entity.getPromotionID() : "");
        txtpromotionName.setText(entity.getPromotionName() != null ? entity.getPromotionName() : "");
        startDate.setText(entity.getStartDate() != null ? entity.getStartDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")) : "");
        endDate.setText(entity.getEndDate() != null ? entity.getEndDate().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")) : "");
        phamtram.setValue((int) (entity.getDiscountPercent() * 100));
    }

    @Override
    public Promotion getForm() {
        Promotion p = new Promotion();
        p.setPromotionID(txtpromotionID.getText().trim());
        p.setPromotionName(txtpromotionName.getText().trim());

        // Kiểm tra và parse ngày với định dạng dd/MM/yyyy
        try {
            if (!startDate.getText().trim().isEmpty()) {
                p.setStartDate(LocalDate.parse(startDate.getText().trim(), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            }
            if (!endDate.getText().trim().isEmpty()) {
                p.setEndDate(LocalDate.parse(endDate.getText().trim(), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Định dạng ngày không hợp lệ! Vui lòng dùng dd/MM/yyyy.");
            return null;
        }

        p.setDiscountPercent(phamtram.getValue() / 100.0f);
        p.setStatus(true); // Mặc định là true, có thể thêm checkbox để thay đổi
        return p;
    }

    @Override
    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tableModel.getModel();
        model.setRowCount(0); // Clear old data

        try {
            PromotionDAOImpl dao = new PromotionDAOImpl();
            List<Promotion> list = dao.findAll(); // Load from DB
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            for (Promotion p : list) {
                model.addRow(new Object[]{
                    p.getPromotionID(),
                    p.getPromotionName(),
                    p.getStartDate() != null ? p.getStartDate().format(formatter) : "",
                    p.getEndDate() != null ? p.getEndDate().format(formatter) : "",
                    (int) (p.getDiscountPercent() * 100) + "%",
                    p.isStatus() ? "Hoạt động" : "Ngừng hoạt động"
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi load dữ liệu khuyến mãi: " + e.getMessage());
        }
    }

    @Override
    public void edit() {
        Promotion entity = items.get(tableModel.getSelectedRow());
        this.setForm(entity);
        this.setEditable(true);

    }

    @Override
    public void create() {
        Promotion p = getForm();
        if (p == null) {
            return;
        }

        if (p.getPromotionID().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã khuyến mãi không được để trống!");
            txtpromotionID.requestFocus();
            return;
        }
        if (p.getPromotionName().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên khuyến mãi không được để trống!");
            txtpromotionName.requestFocus();
            return;
        }
        if (p.getStartDate() == null || p.getEndDate() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ ngày bắt đầu và ngày kết thúc!");
            return;
        }

        PromotionDAOImpl dao = new PromotionDAOImpl();
        try {
            dao.create(p);
            fillToTable();
            clear();
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm khuyến mãi: " + e.getMessage());
        }
    }

    @Override
    public void update() {
        Promotion p = getForm();
        if (p == null) {
            return;
        }

        if (p.getPromotionID().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khuyến mãi để cập nhật!");
            return;
        }

        PromotionDAOImpl dao = new PromotionDAOImpl();
        try {
            dao.update(p);
            fillToTable();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật khuyến mãi: " + e.getMessage());
        }
    }

    @Override
    public void delete() {
        String id = txtpromotionID.getText().trim();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khuyến mãi để xóa!");
            return;
        }

        PromotionDAOImpl dao = new PromotionDAOImpl();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa khuyến mãi này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                dao.deleteById(id);
                fillToTable();
                clear();
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi xóa khuyến mãi: " + e.getMessage());
            }
        }
    }

    @Override
    public void clear() {
        txtpromotionID.setText("");
        txtpromotionName.setText("");
        startDate.setText("");
        endDate.setText("");
        phamtram.setValue(0);
    }

    @Override
    public void setEditable(boolean editable) {
        txtpromotionID.setEnabled(!editable);
        btnCreate.setEnabled(!editable);
        btnUpdate.setEnabled(editable);
        btnDelete.setEnabled(editable);
        int rowCount = tableModel.getRowCount();
    }

    @Override
    public void checkAll() {
        this.setCheckedAll(true);
    }

    @Override
    public void uncheckAll() {
        this.setCheckedAll(false);
    }

    private void setCheckedAll(boolean checked) {
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            tableModel.setValueAt(checked, i, 2);
        }
    }

    @Override
    public void deleteCheckedItems() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveFirst() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void movePrevious() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveNext() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveLast() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void moveTo(int rowIndex) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField btnmasach;
    private javax.swing.JButton btnnhunghoatdong;
    private javax.swing.JComboBox<String> cbopromotion;
    private javax.swing.JTextField endDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JSlider phamtram;
    private javax.swing.JTextField startDate;
    private javax.swing.JTable tableModel;
    private javax.swing.JTextField txtpromotionID;
    private javax.swing.JTextField txtpromotionName;
    // End of variables declaration//GEN-END:variables
}
