/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ThuNghiem;

import BanSach.entity.Book;
import BanSach.ui.SalesJPanel;
import BanSach.ui.SoLuongJDialog;
import java.awt.Frame;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author KHANH HUNG
 */
public class SachPanel extends javax.swing.JPanel {

    /**
     * Creates new form SachPanel
     */
    private Book book;
    private SalesJPanel salesPanel;

    public SachPanel(SalesJPanel salesPanel) {
        initComponents();
        this.salesPanel = salesPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        txtGiaSach = new javax.swing.JTextField();
        btnThemVaoHoaDon = new javax.swing.JButton();
        txtTenSach = new javax.swing.JTextField();
        lblHinhAnh = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(160, 220));
        setMinimumSize(new java.awt.Dimension(160, 220));
        setPreferredSize(new java.awt.Dimension(185, 275));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        txtGiaSach.setText("Giá sách");
        txtGiaSach.setEnabled(false);

        btnThemVaoHoaDon.setText("Thêm vào hóa đơn");
        btnThemVaoHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemVaoHoaDonMouseClicked(evt);
            }
        });

        txtTenSach.setText("Tên sách");
        txtTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSachActionPerformed(evt);
            }
        });

        lblHinhAnh.setText("jLabel1");
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenSach)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGiaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnThemVaoHoaDon))
                            .addComponent(lblHinhAnh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGiaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThemVaoHoaDon)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 544, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSachActionPerformed

    private void btnThemVaoHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemVaoHoaDonMouseClicked
        // TODO add your handling code here:
        this.themSachVaoHoaDon();
    }//GEN-LAST:event_btnThemVaoHoaDonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemVaoHoaDon;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JTextField txtGiaSach;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables

    // Gọi từ sự kiện click nút "Thêm vào hóa đơn"
    public void themSachVaoHoaDon() {
        if (salesPanel != null && book != null) {
            // Lấy cửa sổ cha đúng cách: dùng Frame để truyền vào JDialog
            Frame parent = (Frame) SwingUtilities.getWindowAncestor(this);

            // Tạo dialog chọn số lượng
            SoLuongJDialog dialog = new SoLuongJDialog(parent, true);
            dialog.setVisible(true); // Hiển thị dialog và chờ người dùng chọn

            // Nếu người dùng bấm "Xác nhận"
            if (dialog.isXacNhan()) {
                int soLuong = dialog.getSoLuong(); // Lấy số lượng đã chọn
                if (soLuong > 0) {
                    // Gửi về SalesPanel để xử lý thêm vào hóa đơn
                    salesPanel.onAddToInvoice(book, soLuong);
                }
            }
        }
    }

    public void setBook(Book book) {
        this.book = book;

        txtTenSach.setText(book.getName());
        txtGiaSach.setText("Giá: " + book.getSalePrice() + " VNĐ");

        // Load ảnh nếu có
        try {
            ImageIcon icon = new ImageIcon("images/" + book.getImage());
            Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            lblHinhAnh.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            lblHinhAnh.setText("Không có ảnh");
        }
    }

    public Book getBook() {
        return this.book;
    }

}
